
const functions = require("firebase-functions");
const admin = require("firebase-admin");

admin.initializeApp();

// Whitelist of approved story templates
const TEMPLATE_WHITELIST = [
  "dreamy-forest",
  "starry-night",
  "garden-adventure",
  "ocean-wonders",
  "mountain-echo",
  "moon-explorer",
  "dinosaur-friends",
  "brave-knight",
  "sunbeam-wakeup",
  "firefly-lullaby",
];

exports.generateStory = functions.https.onCall(async (data, context) => {
  // 1. Auth required
  if (!context.auth) {
    throw new functions.https.HttpsError(
      "unauthenticated",
      "The function must be called while authenticated."
    );
  }
  const uid = context.auth.uid;
  const { familyId, childId, templateId } = data;

  // Validate inputs
  if (!familyId || !childId || !templateId) {
    throw new functions.https.HttpsError(
      "invalid-argument",
      "The function must be called with 'familyId', 'childId', and 'templateId' arguments."
    );
  }

  // 2. Validate family ownership
  const familyRef = admin.firestore().collection("families").doc(familyId);
  const familyDoc = await familyRef.get();

  if (!familyDoc.exists || familyDoc.data().ownerUid !== uid) {
    throw new functions.https.HttpsError(
      "permission-denied",
      "You do not have permission to access this family's data."
    );
  }

  // 3. Validate child exists
  const childRef = familyRef.collection("children").doc(childId);
  const childDoc = await childRef.get();

  if (!childDoc.exists) {
    throw new functions.https.HttpsError(
      "not-found",
      "Child document not found."
    );
  }
  // 4. Validate subscription status
  const familyData = familyDoc.data();
  if (familyData.billing?.status !== "active") {
    throw new functions.https.HttpsError(
      "failed-precondition",
      "A valid subscription is required to generate new stories."
    );
  }

  // 5. Validate templateId against a whitelist.
  if (!TEMPLATE_WHITELIST.includes(templateId)) {
    throw new functions.https.HttpsError(
      "permission-denied",
      `Template '${templateId}' is not a valid story template.`
    );
  }

  // 6. Generate the story content using the template's prompt.
  const template = require(`../src/story-templates/${templateId}.json`);
  const prompt = template.prompt;
  const storyTheme = template.theme;

  // TODO: Replace with a real AI call
  const storyContent = "This is a placeholder story. The real story will be generated by an AI model based on the prompt: " + prompt;


  // 7. Save the generated story to Firestore.
  const newStoryRef = await familyRef.collection("stories").add({
    childId: childId,
    templateId: templateId,
    theme: storyTheme,
    content: storyContent,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    isRead: false,
  });

  // 8. Generate signed URLs for voice and image assets.
  const bucket = admin.storage().bucket();
  const voicePath = `voice/v1/${templateId}.mp3`;
  const imagePath = `images/v1/${templateId}.png`;
  const expirationDate = new Date();
  expirationDate.setHours(expirationDate.getHours() + 24);

  const [audioUrl] = await bucket.file(voicePath).getSignedUrl({
    action: "read",
    expires: expirationDate,
  });

  const [imageUrl] = await bucket.file(imagePath).getSignedUrl({
    action: "read",
    expires: expirationDate,
  });


  // 9. Return the structured payload.
  return {
    storyId: newStoryRef.id,
    theme: storyTheme,
    audioUrl,
    imageUrl,
    duration: 180, // Placeholder for audio duration
    createdAt: new Date().toISOString(),
  };
});
