import { generateStory } from './story-engine.mjs';
const app=document.getElementById('app');
const getLib=()=>JSON.parse(localStorage.getItem('urai_library')||'[]');
const setLib=(v)=>localStorage.setItem('urai_library',JSON.stringify(v));
function route(){const h=location.hash||'#home';if(h==='#home')home(); if(h==='#create')create(); if(h==='#library')library(); if(h.startsWith('#story/'))detail(h.split('/')[1]); if(h==='#settings')settings();}
function home(){app.innerHTML=`<section class='card'><h2>Magical stories for families</h2><p>Create safe, bedtime-ready adventures in seconds.</p><a class='btn' href='#create'>Start a story</a></section><section class='card'><h3>Demo Mode</h3><p>No API key needed. Stories are generated locally and saved privately in this browser.</p></section>`}
function create(){app.innerHTML=`<form class='card' id='f'><h2>Create Story</h2><label>Child Name<input class='input' name='childName' required value='Ari'/></label><label>Theme<input class='input' name='theme' required value='Moon Garden'/></label><div class='row'><label>Mood<select name='mood'><option>gentle</option><option>playful</option><option>brave</option></select></label><label>Narrator<select name='narrator'><option>Mom</option><option>Dad</option><option>Grandparent</option><option>Firefly Guide</option></select></label></div><label>Custom prompt<textarea name='prompt' class='input' rows='3' placeholder='A calm journey about friendship'></textarea></label><button class='btn'>Generate Story</button><p id='err'></p></form>`;
 document.getElementById('f').onsubmit=(e)=>{e.preventDefault(); const fd=Object.fromEntries(new FormData(e.target)); try{const story=generateStory(fd); const lib=getLib(); lib.unshift(story); setLib(lib); location.hash=`#story/${story.id}`;}catch(err){document.getElementById('err').textContent=err.message;}}}
function library(){const lib=getLib();if(!lib.length){app.innerHTML=`<div class='card'><h2>Your Library</h2><p>No stories yet. Create your first magical adventure.</p><a href='#create' class='btn'>Create</a></div>`;return;} app.innerHTML=`<div class='card'><h2>Your Library</h2>${lib.map(s=>`<article><h3>${s.title}</h3><p>${new Date(s.createdAt).toLocaleString()}</p><a href='#story/${s.id}'>Open</a> <button data-del='${s.id}'>Delete</button></article><hr/>`).join('')}</div>`; app.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{setLib(getLib().filter(x=>x.id!==b.dataset.del));library();});}
function detail(id){const s=getLib().find(x=>x.id===id);if(!s){app.innerHTML=`<div class='card'><p>Story not found.</p><a href='#library'>Back</a></div>`;return;} app.innerHTML=`<div class='card'><h2>${s.title}</h2><p>${s.body}</p><p><b>Narrator:</b> ${s.narrator}</p><button class='btn' id='speak'>Play narration</button> <button id='share'>Copy</button> <button id='regen'>Regenerate</button></div>`; document.getElementById('speak').onclick=()=>{const u=new SpeechSynthesisUtterance(s.body); speechSynthesis.speak(u);}; document.getElementById('share').onclick=async()=>{await navigator.clipboard.writeText(`${s.title}\n\n${s.body}`); alert('Copied');}; document.getElementById('regen').onclick=()=>{location.hash='#create';};}
function settings(){app.innerHTML=`<div class='card'><h2>Parent Settings</h2><p>Privacy-first defaults enabled. Stories stay on this device in demo mode.</p></div>`}
window.addEventListener('hashchange',route);route();
